
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjczNDExMjEw","is_bot":false,"login":"mageswarankk","name":"Karankumar Mageswaran"},"headRefName":"Karankumar-Location","number":25,"title":"Add Location Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/25"},{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"Carson-University-Controller","number":22,"title":"Add University Service and Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/22"},{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"Carson-University","number":18,"title":"Add University Service and tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/18"}]
