
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"Joseph-ZipCode-Controller","number":20,"title":"Add ZipCode Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/20"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"Joseph-ZipCode","number":19,"title":"Add Zip Code Service","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/19"},{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"Carson-University","number":18,"title":"Add University Service and tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/18"}]
