
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTg3NzQ0","is_bot":false,"login":"rdoumeth","name":""},"headRefName":"Roberto-Tides-Controller","number":33,"title":"Add TidesController and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/33"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"Daniel-Joke-Controller","number":32,"title":"Add Joke Service and Controller, with regarded test","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/32"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"Daniel-Joke","number":29,"title":"Add Joke Service and ServiceTest","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-1/pull/29"}]
